server:
  port: 18081

spring:
  application:
    name: sample-app
    group: com.alibaba.cloud.acm

alibaba:
  acm:
    endpoint: acm.aliyun.com
    namespace: ****
    accessKey: ***
    secretKey: ***
management:
  port: 7002
